# Project information
site_name: Mathematics for Software Engineering
site_url: https://rbrooksdk.github.io/MSE1_25
site_author: Richard Brooks
site_description: Course Page for Mathematics for Software Engineering
docs_dir: .
site_dir: ../site
# Repository information
repo_name: Github
repo_url: https://github.com/RBrooksDK/MSE1_25

# Copyright
copyright: Copyright &copy; 2025 Richard Brooks

# Configurations
theme:
  name: material
  language: en
  # custom_dir: overrides
  favicon: billeder/vialogo_white.png
  logo: billeder/vialogo.png
  icon:
    repo: fontawesome/brands/github
    annotation: material/chevron-right-circle
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: orange
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode
  font:
    text: "VIA Type"
    code: "Roboto Mono"

plugins:
  - same-dir
  - blog
  - search
  - mkdocs_quiz                                     

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/js/all.min.js

extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: material/email
      link: mailto:rib@via.dk
    - icon: fontawesome/brands/github
      link: https://github.com/RBrooksDK/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rbrooks-dk/

extra_css:
  - stylesheets/extra.css

nav:
  - Home: README.md
  - Sessions: 
    - Sessions/README.md
    - 01 Basic Arithmetic and Functions: 01/README.md
    - 02 Numeral Systems: 02/README.md
    - 03 Set Theory: 03/README.md
    - 04 Combinatorics and Probability Theory: 04/README.md
    - 05 Conditional Probabilities and Bayes' Theorem: 05/README.md
    - 06 Descriptive Statistics: 06/README.md
    - 07 Introduction to Linear Algebra: 07/README.md
    - 08 Vectors and Matrices: 08/README.md
    - 09 Matrix Algebra and Determinants: 09/README.md
    - 10 Differentiation of Simple Functions: 10/README.md
    - 11 Gradients and Partial Derivatives: 11/README.md
    - 12 Conclusion and Q&A Session: 12/README.md
  - Resources: pages/online_resources.md
  - Exam: pages/exam.md
  - FAQ: pages/faq.md
  - About: https://rbrooksdk.github.io